package com.IntegrityTechnologies.business_manager.modules.stock.product.variant.service;

import com.IntegrityTechnologies.business_manager.modules.stock.product.variant.model.ProductVariant;
import com.IntegrityTechnologies.business_manager.modules.stock.product.variant.repository.ProductVariantRepository;
import lombok.RequiredArgsConstructor;
import org.apache.pdfbox.pdmodel.*;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.UUID;

/**
 * VariantBarcodePdfService
 *
 * Restores full legacy barcode PDF functionality:
 *  - Single variant label PDF (A6)
 *  - Multi-variant sheet PDF (Letter)
 *  - Product-wide variant barcode PDF
 *
 * Variant is the sole barcode owner.
 */
@Service
@RequiredArgsConstructor
public class VariantBarcodePdfService {

    private final ProductVariantRepository variantRepo;
    private final VariantBarcodeService barcodeService;

    /* ============================================================
       1. SINGLE VARIANT LABEL (A6)
       ============================================================ */
    public File generateSingleLabel(ProductVariant variant) throws IOException {

        // Ensure barcode + image exist
        barcodeService.generateBarcodeIfMissing(variant.getId());

        File pdf = File.createTempFile(
                "variant-barcode-" + variant.getId(),
                ".pdf"
        );

        try (PDDocument doc = new PDDocument()) {

            PDPage page = new PDPage(PDRectangle.A6);
            doc.addPage(page);

            PDImageXObject barcodeImage =
                    PDImageXObject.createFromFile(
                            variant.getBarcodeImagePath(),
                            doc
                    );

            try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {

                float top = page.getMediaBox().getHeight();

                // Title
                cs.beginText();
                cs.setFont(PDType1Font.HELVETICA_BOLD, 14);
                cs.newLineAtOffset(30, top - 30);
                cs.showText("Product Barcode Label");
                cs.endText();

                // Product name
                cs.beginText();
                cs.setFont(PDType1Font.HELVETICA, 12);
                cs.newLineAtOffset(30, top - 55);
                cs.showText("Product: " + variant.getProduct().getName());
                cs.endText();

                // Variant
                cs.beginText();
                cs.setFont(PDType1Font.HELVETICA_OBLIQUE, 11);
                cs.newLineAtOffset(30, top - 75);
                cs.showText("Variant: " + variant.getClassification());
                cs.endText();

                // Barcode image
                cs.drawImage(barcodeImage, 30, top - 160, 220, 60);

                // Barcode text
                cs.beginText();
                cs.setFont(PDType1Font.HELVETICA, 10);
                cs.newLineAtOffset(30, top - 175);
                cs.showText("Barcode: " + variant.getBarcode());
                cs.endText();

                // Footer
                cs.beginText();
                cs.setFont(PDType1Font.HELVETICA, 8);
                cs.newLineAtOffset(30, 20);
                cs.showText("Generated by Integrity Business Manager");
                cs.endText();
            }

            doc.save(pdf);
        }

        return pdf;
    }

    /* ============================================================
       2. MULTI-VARIANT BARCODE SHEET (LETTER)
       ============================================================ */
    public File generateSheet(List<ProductVariant> variants) throws IOException {

        File pdf = File.createTempFile(
                "variant-barcode-sheet-",
                ".pdf"
        );

        try (PDDocument doc = new PDDocument()) {

            PDPage page = new PDPage(PDRectangle.LETTER);
            doc.addPage(page);

            PDPageContentStream cs = new PDPageContentStream(doc, page);

            float margin = 40;
            float y = page.getMediaBox().getHeight() - margin;
            float spacing = 95;

            for (ProductVariant variant : variants) {

                barcodeService.generateBarcodeIfMissing(variant.getId());

                PDImageXObject barcodeImage =
                        PDImageXObject.createFromFile(
                                variant.getBarcodeImagePath(),
                                doc
                        );

                // Page break
                if (y < 130) {
                    cs.close();
                    page = new PDPage(PDRectangle.LETTER);
                    doc.addPage(page);
                    cs = new PDPageContentStream(doc, page);
                    y = page.getMediaBox().getHeight() - margin;
                }

                // Header text
                cs.beginText();
                cs.setFont(PDType1Font.HELVETICA_BOLD, 11);
                cs.newLineAtOffset(margin, y);
                cs.showText(
                        variant.getProduct().getName()
                                + " — "
                                + variant.getClassification()
                );
                cs.endText();

                // Barcode image
                cs.drawImage(barcodeImage, margin, y - 60, 240, 55);

                // Barcode text
                cs.beginText();
                cs.setFont(PDType1Font.HELVETICA, 9);
                cs.newLineAtOffset(margin, y - 72);
                cs.showText(variant.getBarcode());
                cs.endText();

                y -= spacing;
            }

            cs.close();
            doc.save(pdf);
        }

        return pdf;
    }

    /* ============================================================
       3. PRODUCT-WIDE BARCODE PDF
       ============================================================ */
    public File generateProductSheet(UUID productId) throws IOException {

        List<ProductVariant> variants =
                variantRepo.findByProduct_Id(productId);

        if (variants.isEmpty()) {
            throw new IllegalStateException(
                    "No variants found for product: " + productId
            );
        }

        return generateSheet(variants);
    }

    /* ============================================================
       4. CONTROLLER-FRIENDLY WRAPPER
       ============================================================ */
    public File generatePdf(List<ProductVariant> variants) throws IOException {
        if (variants == null || variants.isEmpty()) {
            throw new IllegalArgumentException("No variants supplied");
        }

        if (variants.size() == 1) {
            return generateSingleLabel(variants.get(0));
        }

        return generateSheet(variants);
    }
}